### ISSUE TITLE
제안) index.html과 public 연결 및 html과 css 만들기

### ISSUE THREAD

**Issue by plou102** [7team-FibonaChicken/FibonaChicken#1]
## 설명

index.html의 기본구조를 완성하고, public/의 파일을 연결하겠습니다.
html 파일과 css 파일을 작성하겠습니다.

## 할 일

- [x] index.html 기본구조 만들기
- [x] #2
- [x] html 구조 완성
- [x] css style 완성

## 참조

- [피보나치킨](https://fibonachicken.herokuapp.com/#)

**Comment by ddoyun** [comment]
good!!!
